base_url = "/"
compile_sass = true
title = "IT Partners"
build_search_index = true
generate_feed = true

taxonomies = [
    {name = "tags"},
    {name = "products"},
    {name = "types"}
]

[link_checker]

skip_prefixes = [
    "https://support.microsoft.com/",
    "http://www.microsoftvolumelicensing.com/",
    "https://portal.azure.com/",
    "https://support.office.com/",
    "https://cloudblogs.microsoft.com/",
    "https://o365hq.com/",
    "https://admin.microsoft.com/"
]

[search]
include_title = true
include_description = true
include_content = true
truncate_content_length = 250